show user;
--------------------------------------------------------

--일반회원
drop table user_member;
select * from member;
CREATE TABLE MEMBER(
MID NVARCHAR2 (50) CONSTRAINT PK_USER_MEMBER PRIMARY KEY,
MPASSWORD NVARCHAR2 (50) NOT NULL,
MNAME NVARCHAR2 (50) NOT NULL,
MADDRESS NVARCHAR2 (100) NOT NULL,
MPHONE NVARCHAR2 (13) NOT NULL,
MEMAIL NVARCHAR2 (50) NOT NULL,
MGENDER NVARCHAR2 (5) NOT NULL,
MBIRTH DATE NOT NULL,
NAVERID NVARCHAR2 (30),
KAKAOID NVARCHAR2 (30),
GOOGLEID NVARCHAR2 (30));

--------------------------------------------------------

DROP TABLE GGYM;
--찜 테이블
CREATE TABLE GGYM(
GGYMNUMBER NUMBER CONSTRAINT PK_GGYM PRIMARY KEY,
GGYMOFFICE NVARCHAR2(50) CONSTRAINT FK_GGYMOFFICE REFERENCES COMMEMBER(COMNUMBER) NOT NULL,
GGYMID NVARCHAR2 (20) CONSTRAINT FK_GGYMID REFERENCES MEMBER(MID) NOT NULL );


CREATE SEQUENCE NOTICE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
    
CREATE SEQUENCE GGYM_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;    

--------------------------------------------------------

--기업회원
CREATE TABLE COMMEMBER(
    COMNUMBER NVARCHAR2(12) CONSTRAINT PK_COMMEMBER PRIMARY KEY,
    COMPASSWORD NVARCHAR2(30),
    COMADDRESS1 NVARCHAR2(50),
    COMADDRESS2 NVARCHAR2(50),
    COMADDRESS3 NVARCHAR2(50),
    COMADDRESS4 NVARCHAR2(50),
    COMPHONE NVARCHAR2(13),
    COMPANY NVARCHAR2(20),
    COMOFFICE NVARCHAR2(20));

--------------------------------------------------------
    
DROP TABLE PRODUCT;
select * from product;
--상품테이블
CREATE TABLE PRODUCT (
PNUMBER NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
PNAME NVARCHAR2 (60) NOT NULL,
PPRICE NUMBER NOT NULL,
PINFO NVARCHAR2 (60) NOT NULL,
PCATEGORY NVARCHAR2 (60) NOT NULL,
PCNUMBER NVARCHAR2 (50) CONSTRAINT FK_PRODUCT REFERENCES COMMEMBER(COMNUMBER) NOT NULL,
PCOUNT NUMBER NOT NULL,
PIMAGE NVARCHAR2 (60),
PDATE DATE );    

CREATE SEQUENCE SEQ_PNUMBER
START WITH 1
INCREMENT BY 1
NOCACHE;

--------------------------------------------------------

DROP TABLE REVIEW;
--리뷰 테이블
CREATE TABLE REVIEW (
RNUMBER NUMBER CONSTRAINT PK_REVIEW PRIMARY KEY,
RID NVARCHAR2 (20) CONSTRAINT FK_REVIEW_RID REFERENCES MEMBER(MID) NOT NULL,
RCONTENTS NVARCHAR2 (200) NOT NULL,
RDATE DATE,
PNUMBER NUMBER CONSTRAINT FK_REVIEW REFERENCES PRODUCT(PNUMBER) NOT NULL);

--------------------------------------------------------

DROP TABLE PAYMENT;
--결제 테이블
CREATE TABLE PAYMENT(
PAYNUMBER NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
PAYPRODUCT NUMBER CONSTRAINT FK_PAYPRODUCT REFERENCES PRODUCT(PNUMBER) NOT NULL,
PAYID NVARCHAR2 (30) CONSTRAINT FK_PAYID REFERENCES MEMBER(MID) NOT NULL,
PAYOFFICE NVARCHAR2(50) CONSTRAINT FK_PAYOFFICE REFERENCES COMMEMBER(COMNUMBER) NOT NULL,
PAYGENDER NVARCHAR2(5),
PAYAGE DATE,
PAYDATE DATE);

--------------------------------------------------------

DROP TABLE BASKET;
--장바구니 테이블
CREATE TABLE BASKET(
BANUMBER NUMBER CONSTRAINT PK_BASKET PRIMARY KEY,
PNUMBER NUMBER CONSTRAINT FK_BASKET REFERENCES PRODUCT(PNUMBER) NOT NULL,
BANAME NVARCHAR2 (20) NOT NULL,
BAIMG NVARCHAR2 (100) NOT NULL,
BAID NVARCHAR2 (20) REFERENCES MEMBER(MID) NOT NULL,
BACOUNT NUMBER NOT NULL);

--------------------------------------------------------

DROP TABLE NOTICE;
SELECT * FROM NOTICE;
--보드(공지사항) 테이블
CREATE TABLE NOTICE(
NNUMBER NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
NTITLE NVARCHAR2 (50) NOT NULL,
NCONTENTS NVARCHAR2 (400) NOT NULL,
NDATE DATE,
NHITS NUMBER,
NFILENAME NVARCHAR2 (100));

--------------------------------------------------------















SELECT * FROM COMMEMBER;
SELECT * FROM NOTICE;
SELECT * FROM GGYM;
COMMIT;
